# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
name: project cicd flow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: '1.8'
        distribution: 'adopt'
        cache: maven
    - name: Build with Maven
      run: mvn clean install

    - name: Build & push Docker image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: naveennallappan/signiance-poc
        tags: latest
        registry: docker.io
        dockerfile: Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
  Deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Deploy in EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOSTNAME }}
        username: ${{ secrets.USER_NAME }}
        key: ${{ secrets.AWS_PRIVATE_KEY }}
        port: ${{ secrets.PORT }}
        script: |
          whoami
          sudo su
          docker stop $(docker ps -a -q)
          docker rm $(docker ps -a -q)
          docker image rm naveennallappan/signiance-poc:latest
          docker pull naveennallappan/signiance-poc
          docker images ls
          docker run -d -p 80:8080 naveennallappan/signiance-poc
          sleep 10
          curl http://43.205.239.76/welcome